// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package nutanix

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatCategory is an auto-generated flat version of Category.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCategory struct {
	Key   *string `mapstructure:"key" json:"key" required:"false" cty:"key" hcl:"key"`
	Value *string `mapstructure:"value" json:"value" required:"false" cty:"value" hcl:"value"`
}

// FlatMapstructure returns a new FlatCategory.
// FlatCategory is an auto-generated flat version of Category.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Category) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCategory)
}

// HCL2Spec returns the hcl spec of a Category.
// This spec is used by HCL to read the fields of Category.
// The decoded values from this spec will then be applied to a FlatCategory.
func (*FlatCategory) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"key":   &hcldec.AttrSpec{Name: "key", Type: cty.String, Required: false},
		"value": &hcldec.AttrSpec{Name: "value", Type: cty.String, Required: false},
	}
	return s
}

// FlatClusterConfig is an auto-generated flat version of ClusterConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatClusterConfig struct {
	Username *string `mapstructure:"nutanix_username" required:"false" cty:"nutanix_username" hcl:"nutanix_username"`
	Password *string `mapstructure:"nutanix_password" required:"false" cty:"nutanix_password" hcl:"nutanix_password"`
	Insecure *bool   `mapstructure:"nutanix_insecure" required:"false" cty:"nutanix_insecure" hcl:"nutanix_insecure"`
	Endpoint *string `mapstructure:"nutanix_endpoint" required:"true" cty:"nutanix_endpoint" hcl:"nutanix_endpoint"`
	Port     *int32  `mapstructure:"nutanix_port" required:"false" cty:"nutanix_port" hcl:"nutanix_port"`
}

// FlatMapstructure returns a new FlatClusterConfig.
// FlatClusterConfig is an auto-generated flat version of ClusterConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ClusterConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatClusterConfig)
}

// HCL2Spec returns the hcl spec of a ClusterConfig.
// This spec is used by HCL to read the fields of ClusterConfig.
// The decoded values from this spec will then be applied to a FlatClusterConfig.
func (*FlatClusterConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"nutanix_username": &hcldec.AttrSpec{Name: "nutanix_username", Type: cty.String, Required: false},
		"nutanix_password": &hcldec.AttrSpec{Name: "nutanix_password", Type: cty.String, Required: false},
		"nutanix_insecure": &hcldec.AttrSpec{Name: "nutanix_insecure", Type: cty.Bool, Required: false},
		"nutanix_endpoint": &hcldec.AttrSpec{Name: "nutanix_endpoint", Type: cty.String, Required: false},
		"nutanix_port":     &hcldec.AttrSpec{Name: "nutanix_port", Type: cty.Number, Required: false},
	}
	return s
}

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName           *string             `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType         *string             `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion         *string             `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug               *bool               `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce               *bool               `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError             *string             `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars            map[string]string   `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars       []string            `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	WaitTimeout               *string             `mapstructure:"ip_wait_timeout" cty:"ip_wait_timeout" hcl:"ip_wait_timeout"`
	SettleTimeout             *string             `mapstructure:"ip_settle_timeout" cty:"ip_settle_timeout" hcl:"ip_settle_timeout"`
	WaitAddress               *string             `mapstructure:"ip_wait_address" cty:"ip_wait_address" hcl:"ip_wait_address"`
	Type                      *string             `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	PauseBeforeConnect        *string             `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting"`
	SSHHost                   *string             `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort                   *int                `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername               *string             `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword               *string             `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHKeyPairName            *string             `mapstructure:"ssh_keypair_name" undocumented:"true" cty:"ssh_keypair_name" hcl:"ssh_keypair_name"`
	SSHTemporaryKeyPairName   *string             `mapstructure:"temporary_key_pair_name" undocumented:"true" cty:"temporary_key_pair_name" hcl:"temporary_key_pair_name"`
	SSHTemporaryKeyPairType   *string             `mapstructure:"temporary_key_pair_type" cty:"temporary_key_pair_type" hcl:"temporary_key_pair_type"`
	SSHTemporaryKeyPairBits   *int                `mapstructure:"temporary_key_pair_bits" cty:"temporary_key_pair_bits" hcl:"temporary_key_pair_bits"`
	SSHCiphers                []string            `mapstructure:"ssh_ciphers" cty:"ssh_ciphers" hcl:"ssh_ciphers"`
	SSHClearAuthorizedKeys    *bool               `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys" hcl:"ssh_clear_authorized_keys"`
	SSHKEXAlgos               []string            `mapstructure:"ssh_key_exchange_algorithms" cty:"ssh_key_exchange_algorithms" hcl:"ssh_key_exchange_algorithms"`
	SSHPrivateKeyFile         *string             `mapstructure:"ssh_private_key_file" undocumented:"true" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
	SSHCertificateFile        *string             `mapstructure:"ssh_certificate_file" cty:"ssh_certificate_file" hcl:"ssh_certificate_file"`
	SSHPty                    *bool               `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty"`
	SSHTimeout                *string             `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
	SSHWaitTimeout            *string             `mapstructure:"ssh_wait_timeout" undocumented:"true" cty:"ssh_wait_timeout" hcl:"ssh_wait_timeout"`
	SSHAgentAuth              *bool               `mapstructure:"ssh_agent_auth" undocumented:"true" cty:"ssh_agent_auth" hcl:"ssh_agent_auth"`
	SSHDisableAgentForwarding *bool               `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts      *int                `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts"`
	SSHBastionHost            *string             `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host"`
	SSHBastionPort            *int                `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port"`
	SSHBastionAgentAuth       *bool               `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth"`
	SSHBastionUsername        *string             `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username"`
	SSHBastionPassword        *string             `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password"`
	SSHBastionInteractive     *bool               `mapstructure:"ssh_bastion_interactive" cty:"ssh_bastion_interactive" hcl:"ssh_bastion_interactive"`
	SSHBastionPrivateKeyFile  *string             `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file"`
	SSHBastionCertificateFile *string             `mapstructure:"ssh_bastion_certificate_file" cty:"ssh_bastion_certificate_file" hcl:"ssh_bastion_certificate_file"`
	SSHFileTransferMethod     *string             `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method"`
	SSHProxyHost              *string             `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host"`
	SSHProxyPort              *int                `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port"`
	SSHProxyUsername          *string             `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username"`
	SSHProxyPassword          *string             `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password"`
	SSHKeepAliveInterval      *string             `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout       *string             `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout"`
	SSHRemoteTunnels          []string            `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels" hcl:"ssh_remote_tunnels"`
	SSHLocalTunnels           []string            `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels" hcl:"ssh_local_tunnels"`
	SSHPublicKey              []byte              `mapstructure:"ssh_public_key" undocumented:"true" cty:"ssh_public_key" hcl:"ssh_public_key"`
	SSHPrivateKey             []byte              `mapstructure:"ssh_private_key" undocumented:"true" cty:"ssh_private_key" hcl:"ssh_private_key"`
	WinRMUser                 *string             `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username"`
	WinRMPassword             *string             `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password"`
	WinRMHost                 *string             `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host"`
	WinRMNoProxy              *bool               `mapstructure:"winrm_no_proxy" cty:"winrm_no_proxy" hcl:"winrm_no_proxy"`
	WinRMPort                 *int                `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port"`
	WinRMTimeout              *string             `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout"`
	WinRMUseSSL               *bool               `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl"`
	WinRMInsecure             *bool               `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure"`
	WinRMUseNTLM              *bool               `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm"`
	BootGroupInterval         *string             `mapstructure:"boot_keygroup_interval" cty:"boot_keygroup_interval" hcl:"boot_keygroup_interval"`
	BootWait                  *string             `mapstructure:"boot_wait" cty:"boot_wait" hcl:"boot_wait"`
	BootCommand               []string            `mapstructure:"boot_command" cty:"boot_command" hcl:"boot_command"`
	DisableVNC                *bool               `mapstructure:"disable_vnc" cty:"disable_vnc" hcl:"disable_vnc"`
	BootKeyInterval           *string             `mapstructure:"boot_key_interval" cty:"boot_key_interval" hcl:"boot_key_interval"`
	CDFiles                   []string            `mapstructure:"cd_files" cty:"cd_files" hcl:"cd_files"`
	CDContent                 map[string]string   `mapstructure:"cd_content" cty:"cd_content" hcl:"cd_content"`
	CDLabel                   *string             `mapstructure:"cd_label" cty:"cd_label" hcl:"cd_label"`
	ShutdownCommand           *string             `mapstructure:"shutdown_command" required:"false" cty:"shutdown_command" hcl:"shutdown_command"`
	ShutdownTimeout           *string             `mapstructure:"shutdown_timeout" required:"false" cty:"shutdown_timeout" hcl:"shutdown_timeout"`
	Username                  *string             `mapstructure:"nutanix_username" required:"false" cty:"nutanix_username" hcl:"nutanix_username"`
	Password                  *string             `mapstructure:"nutanix_password" required:"false" cty:"nutanix_password" hcl:"nutanix_password"`
	Insecure                  *bool               `mapstructure:"nutanix_insecure" required:"false" cty:"nutanix_insecure" hcl:"nutanix_insecure"`
	Endpoint                  *string             `mapstructure:"nutanix_endpoint" required:"true" cty:"nutanix_endpoint" hcl:"nutanix_endpoint"`
	Port                      *int32              `mapstructure:"nutanix_port" required:"false" cty:"nutanix_port" hcl:"nutanix_port"`
	VMName                    *string             `mapstructure:"vm_name" json:"vm_name" required:"false" cty:"vm_name" hcl:"vm_name"`
	OSType                    *string             `mapstructure:"os_type" json:"os_type" required:"true" cty:"os_type" hcl:"os_type"`
	BootType                  *string             `mapstructure:"boot_type" json:"boot_type" required:"false" cty:"boot_type" hcl:"boot_type"`
	VTPM                      *FlatVTPM           `mapstructure:"vtpm" json:"vtpm" required:"false" cty:"vtpm" hcl:"vtpm"`
	HardwareVirtualization    *bool               `mapstructure:"hardware_virtualization" json:"hardware_virtualization" required:"false" cty:"hardware_virtualization" hcl:"hardware_virtualization"`
	BootPriority              *string             `mapstructure:"boot_priority" json:"boot_priority" required:"false" cty:"boot_priority" hcl:"boot_priority"`
	VmDisks                   []FlatVmDisk        `mapstructure:"vm_disks" cty:"vm_disks" hcl:"vm_disks"`
	VmNICs                    []FlatVmNIC         `mapstructure:"vm_nics" cty:"vm_nics" hcl:"vm_nics"`
	ImageName                 *string             `mapstructure:"image_name" json:"image_name" required:"false" cty:"image_name" hcl:"image_name"`
	ClusterUUID               *string             `mapstructure:"cluster_uuid" json:"cluster_uuid" required:"false" cty:"cluster_uuid" hcl:"cluster_uuid"`
	ClusterName               *string             `mapstructure:"cluster_name" json:"cluster_name" required:"false" cty:"cluster_name" hcl:"cluster_name"`
	CPU                       *int64              `mapstructure:"cpu" json:"cpu" required:"false" cty:"cpu" hcl:"cpu"`
	Core                      *int64              `mapstructure:"core" json:"core" required:"false" cty:"core" hcl:"core"`
	MemoryMB                  *int64              `mapstructure:"memory_mb" json:"memory_mb" required:"false" cty:"memory_mb" hcl:"memory_mb"`
	UserData                  *string             `mapstructure:"user_data" json:"user_data" required:"false" cty:"user_data" hcl:"user_data"`
	VMCategories              []FlatCategory      `mapstructure:"vm_categories" required:"false" cty:"vm_categories" hcl:"vm_categories"`
	Project                   *string             `mapstructure:"project" required:"false" cty:"project" hcl:"project"`
	GPU                       []FlatGPU           `mapstructure:"gpu" required:"false" cty:"gpu" hcl:"gpu"`
	SerialPort                *bool               `mapstructure:"serialport" json:"serialport" required:"false" cty:"serialport" hcl:"serialport"`
	OvaConfig                 *FlatOvaConfig      `mapstructure:"ova" required:"false" cty:"ova" hcl:"ova"`
	TemplateConfig            *FlatTemplateConfig `mapstructure:"template" required:"false" cty:"template" hcl:"template"`
	ForceDeregister           *bool               `mapstructure:"force_deregister" json:"force_deregister" required:"false" cty:"force_deregister" hcl:"force_deregister"`
	ImageDescription          *string             `mapstructure:"image_description" json:"image_description" required:"false" cty:"image_description" hcl:"image_description"`
	ImageCategories           []FlatCategory      `mapstructure:"image_categories" required:"false" cty:"image_categories" hcl:"image_categories"`
	ImageSkip                 *bool               `mapstructure:"image_skip" json:"image_skip" required:"false" cty:"image_skip" hcl:"image_skip"`
	ImageDelete               *bool               `mapstructure:"image_delete" json:"image_delete" required:"false" cty:"image_delete" hcl:"image_delete"`
	ImageExport               *bool               `mapstructure:"image_export" json:"image_export" required:"false" cty:"image_export" hcl:"image_export"`
	VmForceDelete             *bool               `mapstructure:"vm_force_delete" json:"vm_force_delete" required:"false" cty:"vm_force_delete" hcl:"vm_force_delete"`
	VmRetain                  *bool               `mapstructure:"vm_retain" json:"vm_retain" required:"false" cty:"vm_retain" hcl:"vm_retain"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":            &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":          &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":          &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":                 &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":                 &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":              &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":        &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables":   &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"ip_wait_timeout":              &hcldec.AttrSpec{Name: "ip_wait_timeout", Type: cty.String, Required: false},
		"ip_settle_timeout":            &hcldec.AttrSpec{Name: "ip_settle_timeout", Type: cty.String, Required: false},
		"ip_wait_address":              &hcldec.AttrSpec{Name: "ip_wait_address", Type: cty.String, Required: false},
		"communicator":                 &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"pause_before_connecting":      &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"ssh_host":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_keypair_name":             &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"temporary_key_pair_name":      &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"temporary_key_pair_type":      &hcldec.AttrSpec{Name: "temporary_key_pair_type", Type: cty.String, Required: false},
		"temporary_key_pair_bits":      &hcldec.AttrSpec{Name: "temporary_key_pair_bits", Type: cty.Number, Required: false},
		"ssh_ciphers":                  &hcldec.AttrSpec{Name: "ssh_ciphers", Type: cty.List(cty.String), Required: false},
		"ssh_clear_authorized_keys":    &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"ssh_key_exchange_algorithms":  &hcldec.AttrSpec{Name: "ssh_key_exchange_algorithms", Type: cty.List(cty.String), Required: false},
		"ssh_private_key_file":         &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"ssh_certificate_file":         &hcldec.AttrSpec{Name: "ssh_certificate_file", Type: cty.String, Required: false},
		"ssh_pty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"ssh_timeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"ssh_wait_timeout":             &hcldec.AttrSpec{Name: "ssh_wait_timeout", Type: cty.String, Required: false},
		"ssh_agent_auth":               &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"ssh_disable_agent_forwarding": &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"ssh_handshake_attempts":       &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"ssh_bastion_host":             &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"ssh_bastion_port":             &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"ssh_bastion_agent_auth":       &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"ssh_bastion_username":         &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"ssh_bastion_password":         &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"ssh_bastion_interactive":      &hcldec.AttrSpec{Name: "ssh_bastion_interactive", Type: cty.Bool, Required: false},
		"ssh_bastion_private_key_file": &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"ssh_bastion_certificate_file": &hcldec.AttrSpec{Name: "ssh_bastion_certificate_file", Type: cty.String, Required: false},
		"ssh_file_transfer_method":     &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"ssh_proxy_host":               &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"ssh_proxy_port":               &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"ssh_proxy_username":           &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"ssh_proxy_password":           &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"ssh_keep_alive_interval":      &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"ssh_read_write_timeout":       &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"ssh_remote_tunnels":           &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_local_tunnels":            &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_public_key":               &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"ssh_private_key":              &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"winrm_username":               &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"winrm_password":               &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"winrm_host":                   &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"winrm_no_proxy":               &hcldec.AttrSpec{Name: "winrm_no_proxy", Type: cty.Bool, Required: false},
		"winrm_port":                   &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"winrm_timeout":                &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"winrm_use_ssl":                &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"winrm_insecure":               &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"winrm_use_ntlm":               &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"boot_keygroup_interval":       &hcldec.AttrSpec{Name: "boot_keygroup_interval", Type: cty.String, Required: false},
		"boot_wait":                    &hcldec.AttrSpec{Name: "boot_wait", Type: cty.String, Required: false},
		"boot_command":                 &hcldec.AttrSpec{Name: "boot_command", Type: cty.List(cty.String), Required: false},
		"disable_vnc":                  &hcldec.AttrSpec{Name: "disable_vnc", Type: cty.Bool, Required: false},
		"boot_key_interval":            &hcldec.AttrSpec{Name: "boot_key_interval", Type: cty.String, Required: false},
		"cd_files":                     &hcldec.AttrSpec{Name: "cd_files", Type: cty.List(cty.String), Required: false},
		"cd_content":                   &hcldec.AttrSpec{Name: "cd_content", Type: cty.Map(cty.String), Required: false},
		"cd_label":                     &hcldec.AttrSpec{Name: "cd_label", Type: cty.String, Required: false},
		"shutdown_command":             &hcldec.AttrSpec{Name: "shutdown_command", Type: cty.String, Required: false},
		"shutdown_timeout":             &hcldec.AttrSpec{Name: "shutdown_timeout", Type: cty.String, Required: false},
		"nutanix_username":             &hcldec.AttrSpec{Name: "nutanix_username", Type: cty.String, Required: false},
		"nutanix_password":             &hcldec.AttrSpec{Name: "nutanix_password", Type: cty.String, Required: false},
		"nutanix_insecure":             &hcldec.AttrSpec{Name: "nutanix_insecure", Type: cty.Bool, Required: false},
		"nutanix_endpoint":             &hcldec.AttrSpec{Name: "nutanix_endpoint", Type: cty.String, Required: false},
		"nutanix_port":                 &hcldec.AttrSpec{Name: "nutanix_port", Type: cty.Number, Required: false},
		"vm_name":                      &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"os_type":                      &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"boot_type":                    &hcldec.AttrSpec{Name: "boot_type", Type: cty.String, Required: false},
		"vtpm":                         &hcldec.BlockSpec{TypeName: "vtpm", Nested: hcldec.ObjectSpec((*FlatVTPM)(nil).HCL2Spec())},
		"hardware_virtualization":      &hcldec.AttrSpec{Name: "hardware_virtualization", Type: cty.Bool, Required: false},
		"boot_priority":                &hcldec.AttrSpec{Name: "boot_priority", Type: cty.String, Required: false},
		"vm_disks":                     &hcldec.BlockListSpec{TypeName: "vm_disks", Nested: hcldec.ObjectSpec((*FlatVmDisk)(nil).HCL2Spec())},
		"vm_nics":                      &hcldec.BlockListSpec{TypeName: "vm_nics", Nested: hcldec.ObjectSpec((*FlatVmNIC)(nil).HCL2Spec())},
		"image_name":                   &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"cluster_uuid":                 &hcldec.AttrSpec{Name: "cluster_uuid", Type: cty.String, Required: false},
		"cluster_name":                 &hcldec.AttrSpec{Name: "cluster_name", Type: cty.String, Required: false},
		"cpu":                          &hcldec.AttrSpec{Name: "cpu", Type: cty.Number, Required: false},
		"core":                         &hcldec.AttrSpec{Name: "core", Type: cty.Number, Required: false},
		"memory_mb":                    &hcldec.AttrSpec{Name: "memory_mb", Type: cty.Number, Required: false},
		"user_data":                    &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"vm_categories":                &hcldec.BlockListSpec{TypeName: "vm_categories", Nested: hcldec.ObjectSpec((*FlatCategory)(nil).HCL2Spec())},
		"project":                      &hcldec.AttrSpec{Name: "project", Type: cty.String, Required: false},
		"gpu":                          &hcldec.BlockListSpec{TypeName: "gpu", Nested: hcldec.ObjectSpec((*FlatGPU)(nil).HCL2Spec())},
		"serialport":                   &hcldec.AttrSpec{Name: "serialport", Type: cty.Bool, Required: false},
		"ova":                          &hcldec.BlockSpec{TypeName: "ova", Nested: hcldec.ObjectSpec((*FlatOvaConfig)(nil).HCL2Spec())},
		"template":                     &hcldec.BlockSpec{TypeName: "template", Nested: hcldec.ObjectSpec((*FlatTemplateConfig)(nil).HCL2Spec())},
		"force_deregister":             &hcldec.AttrSpec{Name: "force_deregister", Type: cty.Bool, Required: false},
		"image_description":            &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"image_categories":             &hcldec.BlockListSpec{TypeName: "image_categories", Nested: hcldec.ObjectSpec((*FlatCategory)(nil).HCL2Spec())},
		"image_skip":                   &hcldec.AttrSpec{Name: "image_skip", Type: cty.Bool, Required: false},
		"image_delete":                 &hcldec.AttrSpec{Name: "image_delete", Type: cty.Bool, Required: false},
		"image_export":                 &hcldec.AttrSpec{Name: "image_export", Type: cty.Bool, Required: false},
		"vm_force_delete":              &hcldec.AttrSpec{Name: "vm_force_delete", Type: cty.Bool, Required: false},
		"vm_retain":                    &hcldec.AttrSpec{Name: "vm_retain", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatGPU is an auto-generated flat version of GPU.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatGPU struct {
	Name *string `mapstructure:"name" json:"name" required:"false" cty:"name" hcl:"name"`
}

// FlatMapstructure returns a new FlatGPU.
// FlatGPU is an auto-generated flat version of GPU.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*GPU) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatGPU)
}

// HCL2Spec returns the hcl spec of a GPU.
// This spec is used by HCL to read the fields of GPU.
// The decoded values from this spec will then be applied to a FlatGPU.
func (*FlatGPU) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name": &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}

// FlatOvaConfig is an auto-generated flat version of OvaConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatOvaConfig struct {
	Export *bool   `mapstructure:"export" json:"export" required:"false" cty:"export" hcl:"export"`
	Create *bool   `mapstructure:"create" json:"create" required:"false" cty:"create" hcl:"create"`
	Format *string `mapstructure:"format" json:"format" required:"false" cty:"format" hcl:"format"`
	Name   *string `mapstructure:"name" json:"name" required:"false" cty:"name" hcl:"name"`
}

// FlatMapstructure returns a new FlatOvaConfig.
// FlatOvaConfig is an auto-generated flat version of OvaConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*OvaConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatOvaConfig)
}

// HCL2Spec returns the hcl spec of a OvaConfig.
// This spec is used by HCL to read the fields of OvaConfig.
// The decoded values from this spec will then be applied to a FlatOvaConfig.
func (*FlatOvaConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"export": &hcldec.AttrSpec{Name: "export", Type: cty.Bool, Required: false},
		"create": &hcldec.AttrSpec{Name: "create", Type: cty.Bool, Required: false},
		"format": &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"name":   &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}

// FlatTemplateConfig is an auto-generated flat version of TemplateConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTemplateConfig struct {
	Create      *bool   `mapstructure:"create" json:"create" required:"false" cty:"create" hcl:"create"`
	Name        *string `mapstructure:"name" json:"name" required:"false" cty:"name" hcl:"name"`
	Description *string `mapstructure:"description" json:"description" required:"false" cty:"description" hcl:"description"`
}

// FlatMapstructure returns a new FlatTemplateConfig.
// FlatTemplateConfig is an auto-generated flat version of TemplateConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TemplateConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTemplateConfig)
}

// HCL2Spec returns the hcl spec of a TemplateConfig.
// This spec is used by HCL to read the fields of TemplateConfig.
// The decoded values from this spec will then be applied to a FlatTemplateConfig.
func (*FlatTemplateConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"create":      &hcldec.AttrSpec{Name: "create", Type: cty.Bool, Required: false},
		"name":        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description": &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
	}
	return s
}

// FlatVTPM is an auto-generated flat version of VTPM.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVTPM struct {
	Enabled *bool `mapstructure:"enabled" json:"enabled" required:"false" cty:"enabled" hcl:"enabled"`
}

// FlatMapstructure returns a new FlatVTPM.
// FlatVTPM is an auto-generated flat version of VTPM.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*VTPM) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVTPM)
}

// HCL2Spec returns the hcl spec of a VTPM.
// This spec is used by HCL to read the fields of VTPM.
// The decoded values from this spec will then be applied to a FlatVTPM.
func (*FlatVTPM) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"enabled": &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatVmConfig is an auto-generated flat version of VmConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVmConfig struct {
	VMName                 *string        `mapstructure:"vm_name" json:"vm_name" required:"false" cty:"vm_name" hcl:"vm_name"`
	OSType                 *string        `mapstructure:"os_type" json:"os_type" required:"true" cty:"os_type" hcl:"os_type"`
	BootType               *string        `mapstructure:"boot_type" json:"boot_type" required:"false" cty:"boot_type" hcl:"boot_type"`
	VTPM                   *FlatVTPM      `mapstructure:"vtpm" json:"vtpm" required:"false" cty:"vtpm" hcl:"vtpm"`
	HardwareVirtualization *bool          `mapstructure:"hardware_virtualization" json:"hardware_virtualization" required:"false" cty:"hardware_virtualization" hcl:"hardware_virtualization"`
	BootPriority           *string        `mapstructure:"boot_priority" json:"boot_priority" required:"false" cty:"boot_priority" hcl:"boot_priority"`
	VmDisks                []FlatVmDisk   `mapstructure:"vm_disks" cty:"vm_disks" hcl:"vm_disks"`
	VmNICs                 []FlatVmNIC    `mapstructure:"vm_nics" cty:"vm_nics" hcl:"vm_nics"`
	ImageName              *string        `mapstructure:"image_name" json:"image_name" required:"false" cty:"image_name" hcl:"image_name"`
	ClusterUUID            *string        `mapstructure:"cluster_uuid" json:"cluster_uuid" required:"false" cty:"cluster_uuid" hcl:"cluster_uuid"`
	ClusterName            *string        `mapstructure:"cluster_name" json:"cluster_name" required:"false" cty:"cluster_name" hcl:"cluster_name"`
	CPU                    *int64         `mapstructure:"cpu" json:"cpu" required:"false" cty:"cpu" hcl:"cpu"`
	Core                   *int64         `mapstructure:"core" json:"core" required:"false" cty:"core" hcl:"core"`
	MemoryMB               *int64         `mapstructure:"memory_mb" json:"memory_mb" required:"false" cty:"memory_mb" hcl:"memory_mb"`
	UserData               *string        `mapstructure:"user_data" json:"user_data" required:"false" cty:"user_data" hcl:"user_data"`
	VMCategories           []FlatCategory `mapstructure:"vm_categories" required:"false" cty:"vm_categories" hcl:"vm_categories"`
	Project                *string        `mapstructure:"project" required:"false" cty:"project" hcl:"project"`
	GPU                    []FlatGPU      `mapstructure:"gpu" required:"false" cty:"gpu" hcl:"gpu"`
	SerialPort             *bool          `mapstructure:"serialport" json:"serialport" required:"false" cty:"serialport" hcl:"serialport"`
}

// FlatMapstructure returns a new FlatVmConfig.
// FlatVmConfig is an auto-generated flat version of VmConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*VmConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVmConfig)
}

// HCL2Spec returns the hcl spec of a VmConfig.
// This spec is used by HCL to read the fields of VmConfig.
// The decoded values from this spec will then be applied to a FlatVmConfig.
func (*FlatVmConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"vm_name":                 &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"os_type":                 &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"boot_type":               &hcldec.AttrSpec{Name: "boot_type", Type: cty.String, Required: false},
		"vtpm":                    &hcldec.BlockSpec{TypeName: "vtpm", Nested: hcldec.ObjectSpec((*FlatVTPM)(nil).HCL2Spec())},
		"hardware_virtualization": &hcldec.AttrSpec{Name: "hardware_virtualization", Type: cty.Bool, Required: false},
		"boot_priority":           &hcldec.AttrSpec{Name: "boot_priority", Type: cty.String, Required: false},
		"vm_disks":                &hcldec.BlockListSpec{TypeName: "vm_disks", Nested: hcldec.ObjectSpec((*FlatVmDisk)(nil).HCL2Spec())},
		"vm_nics":                 &hcldec.BlockListSpec{TypeName: "vm_nics", Nested: hcldec.ObjectSpec((*FlatVmNIC)(nil).HCL2Spec())},
		"image_name":              &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"cluster_uuid":            &hcldec.AttrSpec{Name: "cluster_uuid", Type: cty.String, Required: false},
		"cluster_name":            &hcldec.AttrSpec{Name: "cluster_name", Type: cty.String, Required: false},
		"cpu":                     &hcldec.AttrSpec{Name: "cpu", Type: cty.Number, Required: false},
		"core":                    &hcldec.AttrSpec{Name: "core", Type: cty.Number, Required: false},
		"memory_mb":               &hcldec.AttrSpec{Name: "memory_mb", Type: cty.Number, Required: false},
		"user_data":               &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"vm_categories":           &hcldec.BlockListSpec{TypeName: "vm_categories", Nested: hcldec.ObjectSpec((*FlatCategory)(nil).HCL2Spec())},
		"project":                 &hcldec.AttrSpec{Name: "project", Type: cty.String, Required: false},
		"gpu":                     &hcldec.BlockListSpec{TypeName: "gpu", Nested: hcldec.ObjectSpec((*FlatGPU)(nil).HCL2Spec())},
		"serialport":              &hcldec.AttrSpec{Name: "serialport", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatVmDisk is an auto-generated flat version of VmDisk.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVmDisk struct {
	ImageType               *string `mapstructure:"image_type" json:"image_type" required:"false" cty:"image_type" hcl:"image_type"`
	SourceImageName         *string `mapstructure:"source_image_name" json:"source_image_name" required:"false" cty:"source_image_name" hcl:"source_image_name"`
	SourceImageUUID         *string `mapstructure:"source_image_uuid" json:"source_image_uuid" required:"false" cty:"source_image_uuid" hcl:"source_image_uuid"`
	SourceImageURI          *string `mapstructure:"source_image_uri" json:"source_image_uri" required:"false" cty:"source_image_uri" hcl:"source_image_uri"`
	SourceImageChecksum     *string `mapstructure:"source_image_checksum" json:"source_image_checksum" required:"false" cty:"source_image_checksum" hcl:"source_image_checksum"`
	SourceImageChecksumType *string `mapstructure:"source_image_checksum_type" json:"source_image_checksum_type" required:"false" cty:"source_image_checksum_type" hcl:"source_image_checksum_type"`
	SourceImageDelete       *bool   `mapstructure:"source_image_delete" json:"source_image_delete" required:"false" cty:"source_image_delete" hcl:"source_image_delete"`
	SourceImageForce        *bool   `mapstructure:"source_image_force" json:"source_image_force" required:"false" cty:"source_image_force" hcl:"source_image_force"`
	DiskSizeGB              *int64  `mapstructure:"disk_size_gb" json:"disk_size_gb" required:"false" cty:"disk_size_gb" hcl:"disk_size_gb"`
}

// FlatMapstructure returns a new FlatVmDisk.
// FlatVmDisk is an auto-generated flat version of VmDisk.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*VmDisk) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVmDisk)
}

// HCL2Spec returns the hcl spec of a VmDisk.
// This spec is used by HCL to read the fields of VmDisk.
// The decoded values from this spec will then be applied to a FlatVmDisk.
func (*FlatVmDisk) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image_type":                 &hcldec.AttrSpec{Name: "image_type", Type: cty.String, Required: false},
		"source_image_name":          &hcldec.AttrSpec{Name: "source_image_name", Type: cty.String, Required: false},
		"source_image_uuid":          &hcldec.AttrSpec{Name: "source_image_uuid", Type: cty.String, Required: false},
		"source_image_uri":           &hcldec.AttrSpec{Name: "source_image_uri", Type: cty.String, Required: false},
		"source_image_checksum":      &hcldec.AttrSpec{Name: "source_image_checksum", Type: cty.String, Required: false},
		"source_image_checksum_type": &hcldec.AttrSpec{Name: "source_image_checksum_type", Type: cty.String, Required: false},
		"source_image_delete":        &hcldec.AttrSpec{Name: "source_image_delete", Type: cty.Bool, Required: false},
		"source_image_force":         &hcldec.AttrSpec{Name: "source_image_force", Type: cty.Bool, Required: false},
		"disk_size_gb":               &hcldec.AttrSpec{Name: "disk_size_gb", Type: cty.Number, Required: false},
	}
	return s
}

// FlatVmNIC is an auto-generated flat version of VmNIC.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVmNIC struct {
	SubnetName *string `mapstructure:"subnet_name" json:"subnet_name" required:"false" cty:"subnet_name" hcl:"subnet_name"`
	SubnetUUID *string `mapstructure:"subnet_uuid" json:"subnet_uuid" required:"false" cty:"subnet_uuid" hcl:"subnet_uuid"`
}

// FlatMapstructure returns a new FlatVmNIC.
// FlatVmNIC is an auto-generated flat version of VmNIC.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*VmNIC) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVmNIC)
}

// HCL2Spec returns the hcl spec of a VmNIC.
// This spec is used by HCL to read the fields of VmNIC.
// The decoded values from this spec will then be applied to a FlatVmNIC.
func (*FlatVmNIC) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"subnet_name": &hcldec.AttrSpec{Name: "subnet_name", Type: cty.String, Required: false},
		"subnet_uuid": &hcldec.AttrSpec{Name: "subnet_uuid", Type: cty.String, Required: false},
	}
	return s
}
