name: Black Duck Daily Policy Check
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  security:
    if: github.repository == 'nutanix-cloud-native/packer-plugin-nutanix'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Project
        run: make build

      - name: Black Duck Full Scan
        uses: blackduck-inc/black-duck-security-scan@v2.2.1
        with:
          blackducksca_url : ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackducksca_scan_full : true
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'